spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false #禁用模板引擎的缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_vue?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idel: 0
    timeout: 10000

server:
  port: 5421
  max-http-header-size: 18432